import Head from "next/head";
import { Hero } from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <h1 className="font-bold text-center text-indigo-700">Hola Mundo</h1>
      </main>
    </div>
  );
}
